### ISSUE TITLE
Call to undefined method App\Notifications\PaymentLinkNotification::toWhatsApp() 

### ISSUE THREAD

**Issue by ipanardian** [ammezie/laravel-whatsapp-notification#7]
Hi, hope you have a nice day. I just want to report got an error. 

`Call to undefined method App\Notifications\PaymentLinkNotification::toWhatsApp() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Notifications\\PaymentLinkNotification::toWhatsApp() at /Users/ipanardian/workspace/titikpintar/backend-user-ms/app/Channels/WhatsAppChannel.php:12)`

I followed your code but still got this error. Did I missing something? Thanks

**Comment by ipanardian** [comment]
Somehow it's working now, no idea

**Comment by hapackcis-git** [comment]
hlo
how did you get the solution
can you please tell me the step
